# Generated by Django 5.0.3 on 2024-06-12 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gedung_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasigedung',
            name='id_peminjam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
