# Generated by Django 5.0.3 on 2024-07-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reservasigedung_id_peminjam_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gedung',
            name='deskripsi_gedung',
            field=models.TextField(null=True),
        ),
    ]
